version: '3'
services:
  db:
     image: mysql:5.7
     ports:
      - '3306:3306'
     container_name: 'mysql'
     restart: always
     volumes:
       - db_data:/var/lib/mysql
     environment:
       MYSQL_ROOT_PASSWORD: pgpassword
       MYSQL_DATABASE: dbapienade
       MYSQL_USER: pgsql
       MYSQL_PASSWORD: pgpassword
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db_data: {}
  api-logs:
